server:
  port: 8080

spring:
  application:
    name: allica-test-mvc
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG
